### ISSUE TITLE
New links to Android SDKs

### ISSUE THREAD

**Issue by jpsjanne** [nubomedia/developer-guidelines#5]
Hi, the Android SDK links are out of date. I believe that I cannot create a pull request since I don't have push permission, so could somebody either give me the proper rights or update the contents of android.md. The new content is in here (extension changed to txt since GitHub doesn't allow uploading a file with .md extension):

[android.txt](https://github.com/nubomedia/developer-guidelines/files/526370/android.txt)

**Comment by bonigarcia** [comment]
Hi,

You don't have push permission but still you can create PRs. See [doc](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) for further info. Next time please do it by means of PRs, I will push changes to master branch.

For this patch, I updated [android.md](https://github.com/nubomedia/developer-guidelines/blob/master/docs/sdk/android.md) with your changes.

Kind regards

**Comment by jpsjanne** [comment]
Ok, thanks!
